### ISSUE TITLE
AWS version pinning

### ISSUE THREAD

**Issue by Almenon** [aws-ia/terraform-aws-mwaa#21]
I noticed that the AWS provider version is pinned to 4.20, is there a reason for that? 

For context I'm wondering because this conflicts with the version requirement of https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_parameter_group/versions.tf

https://github.com/aws-ia/terraform-aws-mwaa/blob/main/versions.tf

**Comment by vara-bonthu** [comment]
@Almenon No specific requirement. Please feel free to raise a PR to change that to `>=`
