### ISSUE TITLE
Security issue: MWAA has more access than it needs

### ISSUE THREAD

**Issue by Almenon** [aws-ia/terraform-aws-mwaa#26]
MWAA has `"eks:*"` access, but it does not need EKS access by default. It does not need S3 delete permissions by default either. Finally, I don't think it needs `batch` permissions. 

https://github.com/aws-ia/terraform-aws-mwaa/pull/23 fixes this.

**Comment by monometa** [comment]
@vara-bonthu Hi, just a note: I believe that the issue was resolved by merging https://github.com/aws-ia/terraform-aws-mwaa/pull/49 and might be closed to avoid confusion
