### ISSUE TITLE
Add support for startup scripts

### ISSUE THREAD

**Issue by easontm** [aws-ia/terraform-aws-mwaa#28]
The `mwaa_environment` [resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mwaa_environment#startup_script_s3_path) now supports `startup_script_s3_path` and `startup_script_s3_object_version`.

This would be a nice addition to the provider :)

(note: this issue was created with the intention of making a PR for it myself, I will edit this comment if I cannot do so for some reason)

**Comment by vara-bonthu** [comment]
PR is now merged. Closing the issue. Thanks
